import * as T from 'three';
import {GLTFLoader} from './GLTFLoader.js';
const $=s=>document.querySelector(s), panel=$('#panel'), visited=new Set();
const places=[{name:'The ceremony',short:'Ceremony',x:0,z:-3.7,tx:0,tz:-1.8,title:'Where forever begins',intro:'Under the palms, surrounded by our favourite people. Join us for the moment we begin our next chapter.',rows:[['Wedding day','Date & time to be confirmed'],['Ceremony venue','Kerala · exact venue to be confirmed'],['The couple','Names to be confirmed']]},{name:'The celebrations',short:'Celebrations',x:-4.2,z:1.3,tx:-2.7,tz:2.1,title:'A little colour. A lot of joy.',intro:'Come for the celebration. Stay for the laughter, the stories, and a meal shared together.',rows:[['Wedding festivities','Events & timings to be confirmed'],['Dress code','Details to follow']]},{name:'Getting here',short:'Travel',x:4.4,z:2.5,tx:3.1,tz:2.6,title:'Find your way to us',intro:'Your journey ends here, by the backwaters. We’ll share everything you need to arrive with ease.',rows:[['Venue & directions','Exact address and map to follow'],['Stay & travel','Accommodation details to follow'],['RSVP','Contact and reply date to be confirmed']]}];
function content(p){return `<span class="eyebrow">${p.name.toUpperCase()}</span><h2 id="panel-title">${p.title}</h2><p>${p.intro}</p>${p.rows.map(([a,b])=>`<div class="detail-row"><strong>${a}</strong><span>${b}</span></div>`).join('')}<button class="panel-action" id="continue">Back to our little world</button>`}
function show(html){$('#panel-content').innerHTML=html;panel.showModal();$('#continue')?.addEventListener('click',()=>panel.close());}
function openPlace(i){visited.add(i);document.querySelectorAll('.place')[i]?.classList.add('visited');$('#progress').innerHTML=places.map((_,j)=>visited.has(j)?'●':'○').join(' &nbsp; ')+` <span>${visited.size} of 3 places discovered</span>`;show(content(places[i]));}
$('#close').onclick=()=>panel.close();panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)panel.close();}});
$('#details').onclick=()=>show(`<span class="eyebrow">THE INVITATION</span><h2 id="panel-title">All the lovely details</h2><p>Everything you need, without taking a single step.</p><span class="tag">Prototype · details unconfirmed</span>${places.map(p=>`<h3>${p.name}</h3>${p.rows.map(([a,b])=>`<div class="detail-row"><strong>${a}</strong><span>${b}</span></div>`).join('')}`).join('')}<button class="panel-action" id="continue">Back to the island</button>`);
$('#credits').onclick=()=>show('<span class="eyebrow">MADE WITH CARE</span><h2 id="panel-title">A little piece of Kerala</h2><p>An invitation prototype. Wedding names, dates, venues and RSVP details are not yet confirmed.</p><p>Walk with the thumb control, arrow keys or WASD. Swipe or drag the open world to turn it, or tap a place to walk there automatically. Escape closes a panel.</p><p>Palms, plants, flowers, rocks and canoe: <a href="https://kenney.nl/assets/nature-kit" target="_blank" rel="noopener">Kenney Nature Kit</a> (CC0). Built with Three.js.</p><button class="panel-action" id="continue">Back to the island</button>');
async function start(){
const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.outputColorSpace=T.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;$('#canvas').append(renderer.domElement);renderer.domElement.setAttribute('aria-label','A miniature tropical island with a ceremony pavilion, celebration courtyard and canoe jetty');
const scene=new T.Scene();scene.background=new T.Color('#245e62');scene.fog=new T.Fog('#245e62',30,75);const camera=new T.OrthographicCamera(-12,12,12,-12,.1,100);const cameraRadius=Math.hypot(11,18),cameraHeight=17;let cameraAngle=Math.atan2(11,18),turning=false,turnPointer=null,turnStartX=0,turnStartAngle=cameraAngle,lastWorldInput=0;function updateCamera(){camera.position.set(Math.sin(cameraAngle)*cameraRadius,cameraHeight,Math.cos(cameraAngle)*cameraRadius);camera.lookAt(0,0,0)}updateCamera();
scene.add(new T.HemisphereLight('#fff2d0','#327069',2.6));const sun=new T.DirectionalLight('#ffe6af',3.2);sun.position.set(-10,20,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-14,right:14,top:14,bottom:-14});sun.shadow.bias=-.001;scene.add(sun);
const mat=c=>new T.MeshStandardMaterial({color:c,roughness:1,flatShading:true});const materials={green:mat('#6f974a'),sand:mat('#d8c087'),earth:mat('#8a6b46'),wood:mat('#765032'),cream:mat('#f4e4b4'),roof:mat('#b26740'),gold:mat('#e6aa43'),pink:mat('#d77679')};
function mesh(g,m,x=0,y=0,z=0,parent=scene){const o=new T.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o}function box(w,h,d,m,x,y,z,parent=scene){return mesh(new T.BoxGeometry(w,h,d),m,x,y,z,parent)}
const water=mesh(new T.PlaneGeometry(200,200),mat('#2f7b7d'),0,-.66,0);water.rotation.x=-Math.PI/2;water.castShadow=false;
mesh(new T.CylinderGeometry(7.7,6.8,1.2,12),materials.earth,0,-.35,0);mesh(new T.CylinderGeometry(7.9,7.6,.2,12),materials.sand,0,.3,0);mesh(new T.CylinderGeometry(7.55,7.65,.16,12),materials.green,0,.45,0);
// The paths are walkable terrain; the small pavilion is custom game geometry.
function path(ax,az,bx,bz,w=1.2){const dx=bx-ax,dz=bz-az;const o=box(w,.03,Math.hypot(dx,dz),materials.sand,(ax+bx)/2,.55,(az+bz)/2);o.rotation.y=Math.atan2(dx,dz);}
path(0,6,0,-4);path(0,1,-4.8,1.3);path(0,2,5.4,2.5);
const pavilion=new T.Group();pavilion.position.set(0,.6,-3.7);scene.add(pavilion);box(3.4,.25,2.8,materials.cream,0,0,0,pavilion);for(const x of [-1.4,1.4])for(const z of [-1.1,1.1]){box(.16,2.25,.16,materials.cream,x,1.2,z,pavilion);for(let j=0;j<6;j++)mesh(new T.IcosahedronGeometry(.11),materials.gold,x,.5+j*.29,z+.05,pavilion);}const roof=mesh(new T.ConeGeometry(2.6,1.1,4),materials.roof,0,2.8,0,pavilion);roof.rotation.y=Math.PI/4;roof.scale.z=.85;box(3.9,.14,3.3,materials.wood,0,2.24,0,pavilion);box(1.2,.12,.4,materials.cream,0,-.07,1.6,pavilion);for(const x of [-.55,.55])box(.45,.6,.45,materials.gold,x,.42,0,pavilion);
const party=new T.Group();party.position.set(-4.2,.58,1.3);scene.add(party);mesh(new T.CylinderGeometry(1.55,1.55,.13,24),materials.sand,0,0,0,party);for(const x of [-1.25,1.25])box(.09,1.9,.09,materials.wood,x,.95,0,party);for(let j=0;j<9;j++){const x=-1.25+j*.3125;mesh(new T.IcosahedronGeometry(.13),j%2?materials.pink:materials.gold,x,1.75-Math.sin(j/8*Math.PI)*.28,0,party)}for(let j=0;j<4;j++){const a=j*Math.PI/2;mesh(new T.CylinderGeometry(.32,.32,.3,12),materials.cream,Math.cos(a)*.9,.22,Math.sin(a)*.9,party)}
for(let j=0;j<10;j++)box(1.55,.15,.28,materials.wood,5.35,.55,2+j*.3);for(const x of [4.68,6.02])for(const z of [2.1,4.6])box(.12,1,.12,materials.wood,x,.45,z);
const loader=new GLTFLoader();const names=['tree_palmDetailedTall','tree_palmBend','flower_yellowA','flower_redA','plant_bush','rock_largeA','canoe'];const models=await Promise.all(names.map(n=>loader.loadAsync(`assets/${n}.glb`)));const asset=(i,x,z,height,rot=0,y=.55)=>{const o=models[i].scene.clone(true);const b=new T.Box3().setFromObject(o),size=b.getSize(new T.Vector3());o.scale.setScalar(height/size.y);o.position.set(x,y-b.min.y*o.scale.y,z);o.rotation.y=rot;o.traverse(m=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true;}});scene.add(o);return o};
[[0,-5.3,-2.7,4],[1,4.4,-3.6,4.4],[0,-3.3,-5,3.8],[1,2.8,-5.8,4],[0,6,-.5,3.9],[1,-6,2.9,3.4],[0,-3.8,4.8,3.5],[1,2.8,5,3.1]].forEach(([i,x,z,h],j)=>asset(i,x,z,h,j*.8));
for(let i=0;i<24;i++){const a=i*2.399,r=6+Math.sin(i*4)*.65;asset(4,Math.cos(a)*r,Math.sin(a)*r,.45+(i%3)*.12,i)}for(let i=0;i<20;i++){const x=(i%2?1:-1)*(.87+Math.sin(i)*.1),z=-1.5+Math.floor(i/2)*.62;asset(i%2?2:3,x,z,.26,i)}for(let i=0;i<7;i++)asset(5,-6+i*.7,-3.8-i%2,.55+i%3*.15,i);const canoe=asset(6,6.5,3.6,.38,-.35,-.4);
const player=new T.Group();player.position.set(0,.58,4.5);scene.add(player);mesh(new T.CylinderGeometry(.17,.23,.5,8),materials.cream,0,.58,0,player);const skin=mat('#c98d5e');mesh(new T.IcosahedronGeometry(.2,2),skin,0,.99,0,player);mesh(new T.SphereGeometry(.205,8,6,0,Math.PI*2,0,Math.PI/2),materials.wood,0,1.03,0,player);const legs=[box(.12,.3,.14,materials.wood,-.105,.19,0,player),box(.12,.3,.14,materials.wood,.105,.19,0,player)];for(const x of [-.27,.27])box(.11,.36,.13,skin,x,.61,0,player);const ring=mesh(new T.RingGeometry(.32,.43,32),new T.MeshBasicMaterial({color:'#fff0ad',side:T.DoubleSide}),0,.57,4.5);ring.rotation.x=-Math.PI/2;
const labels=places.map((p,i)=>{const b=document.createElement('button');b.className='place';b.innerHTML=`<span class="number">0${i+1}</span>${p.short}`;b.setAttribute('aria-label',`Walk to ${p.name}`);$('#labels').append(b);b.onclick=()=>{target=new T.Vector2(p.tx,p.tz);selected=i};return b});
let target=null,selected=null,near=-1,joy=new T.Vector2(),keys=new Set(),elapsed=0;const right=new T.Vector3(),forward=new T.Vector3(),worldUp=new T.Vector3(0,1,0);renderer.domElement.addEventListener('pointerdown',e=>{turning=true;turnPointer=e.pointerId;turnStartX=e.clientX;turnStartAngle=cameraAngle;lastWorldInput=performance.now();renderer.domElement.setPointerCapture(e.pointerId)});renderer.domElement.addEventListener('pointermove',e=>{if(!turning||e.pointerId!==turnPointer)return;cameraAngle=turnStartAngle-(e.clientX-turnStartX)*.008;lastWorldInput=performance.now();updateCamera()});function stopTurn(e){if(e&&e.pointerId!==turnPointer)return;turning=false;turnPointer=null;lastWorldInput=performance.now()}renderer.domElement.addEventListener('pointerup',stopTurn);renderer.domElement.addEventListener('pointercancel',stopTurn);
function resize(){const w=$('#world').clientWidth,h=$('#world').clientHeight;renderer.setSize(w,h);const width=w<700?18:Math.max(25,w/h*20);camera.left=-width/2;camera.right=width/2;camera.top=width*h/w/2;camera.bottom=-camera.top;camera.updateProjectionMatrix();}resize();window.addEventListener('resize',resize);new ResizeObserver(resize).observe($('#world'));
const stick=$('#joystick');function updateJoy(e){const r=stick.getBoundingClientRect();joy.set((e.clientX-r.left-r.width/2)/32,(e.clientY-r.top-r.height/2)/32);if(joy.length()>1)joy.normalize();$('#thumb').style.transform=`translate(${joy.x*27}px,${joy.y*27}px)`;target=null;}stick.onpointerdown=e=>{stick.setPointerCapture(e.pointerId);updateJoy(e)};stick.onpointermove=e=>{if(stick.hasPointerCapture(e.pointerId))updateJoy(e)};function stop(){joy.set(0,0);keys.clear();$('#thumb').style.transform='';}stick.onpointerup=stop;stick.onpointercancel=stop;window.addEventListener('blur',stop);document.addEventListener('visibilitychange',stop);panel.addEventListener('close',stop);window.addEventListener('keydown',e=>{if(!panel.open&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)){keys.add(e.key);target=null;e.preventDefault()}if(!panel.open&&(e.key==='Enter'||e.key===' ')&&e.target===document.body&&near>=0){e.preventDefault();openPlace(near)}});window.addEventListener('keyup',e=>keys.delete(e.key));$('#reset').onclick=()=>{target=null;selected=null;stop();player.position.set(0,.58,4.5)};$('#interact').onclick=()=>{if(near>=0)openPlace(near)};
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const clock=new T.Clock();$('#loading').remove();
function frame(){requestAnimationFrame(frame);const dt=Math.min(clock.getDelta(),.05);elapsed+=dt;if(!reduced&&!panel.open&&!turning&&!target&&joy.length()<.02&&keys.size===0&&performance.now()-lastWorldInput>1200){cameraAngle+=dt*.075;updateCamera()}right.set(1,0,0).applyQuaternion(camera.quaternion);right.y=0;right.normalize();forward.crossVectors(worldUp,right).normalize();let v=new T.Vector3();if(!panel.open){if(target){v.set(target.x-player.position.x,0,target.y-player.position.z);if(v.length()<.1){target=null;if(selected!==null){openPlace(selected);selected=null}}else v.normalize()}else{let x=joy.x+(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0),y=joy.y+(keys.has('s')||keys.has('ArrowDown')?1:0)-(keys.has('w')||keys.has('ArrowUp')?1:0);v.addScaledVector(right,x).addScaledVector(forward,-y);if(v.length()>1)v.normalize()}if(v.length()>.02){lastWorldInput=performance.now();const next=player.position.clone().addScaledVector(v,2.7*dt);if(Math.hypot(next.x,next.z)<6.75&&!(Math.abs(next.x)<1.9&&next.z<-2.15)){player.position.copy(next)}player.rotation.y=Math.atan2(v.x,v.z);legs[0].rotation.x=Math.sin(elapsed*12)*.45;legs[1].rotation.x=-legs[0].rotation.x;}else legs.forEach(l=>l.rotation.x=0)}ring.position.x=player.position.x;ring.position.z=player.position.z;near=places.findIndex(p=>Math.hypot(player.position.x-p.tx,player.position.z-p.tz)<1.2);$('#interact').disabled=near<0;$('#interact').innerHTML=near>=0?`Open ${places[near].short.toLowerCase()} <span>✦</span>`:'Walk to a place <span>✦</span>';const w=$('#world').clientWidth,h=$('#world').clientHeight;places.forEach((p,i)=>{const a=new T.Vector3(p.x,3.2,p.z).project(camera);labels[i].style.left=`${(a.x*.5+.5)*w}px`;labels[i].style.top=`${(-a.y*.5+.5)*h}px`});if(!reduced){canoe.position.y=-.4+Math.sin(elapsed*1.3)*.045;canoe.rotation.z=Math.sin(elapsed)*.035;}renderer.render(scene,camera)}frame();
}
start().catch(e=>{console.error(e);$('#loading').textContent='The island couldn’t load. Your invitation details are still available above.';$('#loading').style.width='min(320px,80%)';$('.controls').style.display='none';});
